### PR TITLE
edited effects and globe demo

### PR DESCRIPTION
**Pull request by imkumr**

### CODE REVIEW

**Comment by kartikm** [comment]
While these movies are better, one will prefer it stored in localhost? @pranavmistry, comments?

**Comment by imkumr** [comment]
@kartikm,@pranavmistry, : Ya I agree with you but It was actually not working ...as the file is not present in the local host so I thought of adding the webpages instead.

If you think localhost can be better option then we should add another file in the github code and give instructions to people to add it to the location  (C:\inetpub\wwwroot )
I guess this where you have store these swf  files....or am i going wrong somewhere ..?

**Comment by Poincare** [comment]
I heavily disagree with this change, and for several reasons. 
1. what about people not connected to the internet? 
2. what if tomorrow morning mr.doob changes his directory structure?
3. We should try to get rid of SWFs in general; Adobe Flash is dying, as Adobe has shown us time and time again (e.g. got rid of mobile Flash)
4. Additional documentation isn't a problem; hackjobbing something so we don't have to write docs is not acceptable

And, I think we should keep the code as far from the filesystem as possible, because everytime we have something with "C:/" in it, we're moving one step further from this code running on Mono.

**Comment by imkumr** [comment]
@Poincare : First of all, the code uses Internet (without internet it wont run).
And the code also uses local host to run these files and presently these files are not present in the code.
So why cant we use those html pages  for "temporary basis"?

 "something is better than nothing"

Ya,I agree that flash is dying....so we should get rid of those swf files as soon as possible.

**Comment by Poincare** [comment]
Because the current code won't run without internet doesn't mean we should add more internet dependencies.

And, "something is better than nothing" doesn't apply in engineering; broken functionality is worse than no functionality.

The app is useable without the SWF files; let's replace them instead of hacking them on.

**Comment by imkumr** [comment]
The code also uses active x ....and if u havnt installed it...it wont run...! There are many such dlls that the code uses and
I made the changes according to the code...I could have also added a few more lines to the code but that would not have fixed the issue. And that was just an alternative....
I also agree with what you said like flash is outdated so we should now move on .....!

**Comment by Poincare** [comment]
I'm not sure if you understand what I'm saying.

I'm not saying that what you're fixing isn't a problem; it is. But, the solution to it isn't to re-enable the flash files, its just to get rid of them. 

Consider it like this.

If we get rid of the flash files, we still have a functioning application, and, we're moving in the direction of getting rid of useless DLL's. If we re-introduce the flash files, we're moving in the direction of _keeping_ the flash.

@kartikm @pranavmistry comments?

**Comment by imkumr** [comment]
yep buddy..!

**Comment by Poincare** [comment]
Okay, so, lets add this as an issue, but, lets close the pull request.

**Comment by kartikm** [comment]
Closing as requested.

**Pull request closed without merging**
